apiVersion: v1
kind: Service
metadata:
  name: detail
  labels:
    app: detail
spec:
  ports:
    - port: 8081
      name: http
  selector:
    app: detail
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: detail
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: detail
    spec:
      containers:
        - name: detail
          image: detail:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081